# Generated by Django 5.2.11 on 2026-03-01 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('scheduleid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('scheduledate', models.DateField()),
                ('scheduletime', models.TimeField()),
                ('nop', models.IntegerField()),
                ('docid', models.ForeignKey(db_column='docid', on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
            ],
            options={
                'db_table': 'schedule',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appoid', models.AutoField(primary_key=True, serialize=False)),
                ('apponum', models.IntegerField()),
                ('appodate', models.DateField()),
                ('pid', models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
                ('scheduleid', models.ForeignKey(db_column='scheduleid', on_delete=django.db.models.deletion.CASCADE, to='admin_panel.schedule')),
            ],
            options={
                'db_table': 'appointment',
            },
        ),
    ]
