# Generated by Django 5.2.11 on 2026-03-01 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebUser',
            fields=[
                ('email', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('usertype', models.CharField(choices=[('a', 'Admin'), ('d', 'Doctor'), ('p', 'Patient')], max_length=1)),
            ],
            options={
                'db_table': 'webuser',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('aemail', models.OneToOneField(db_column='aemail', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.webuser')),
                ('apassword', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
    ]
