# Generated by Django 5.2.11 on 2026-03-01 22:16

from django.db import migrations


def create_admin_user(apps, schema_editor):
    WebUser = apps.get_model('accounts', 'WebUser')
    Admin = apps.get_model('accounts', 'Admin')

    # Create WebUser
    web_user = WebUser.objects.create(
        email='admin@hms.com',
        usertype='a'
    )

    # Create Admin
    Admin.objects.create(
        aemail=web_user,
        apassword='admin123'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_admin_user),
    ]
