# Generated by Django 5.2.11 on 2026-03-01 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=255)),
                ('ppassword', models.CharField(max_length=255)),
                ('paddress', models.CharField(max_length=255)),
                ('pnic', models.CharField(max_length=255)),
                ('ptel', models.CharField(max_length=255)),
                ('pdob', models.DateField()),
                ('pemail', models.OneToOneField(db_column='pemail', on_delete=django.db.models.deletion.CASCADE, to='accounts.webuser')),
            ],
            options={
                'db_table': 'patient',
            },
        ),
    ]
