# Generated by Django 5.2.11 on 2026-03-01 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialties',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'specialties',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('docid', models.AutoField(primary_key=True, serialize=False)),
                ('docname', models.CharField(max_length=255)),
                ('docpassword', models.CharField(max_length=255)),
                ('docnic', models.CharField(max_length=255)),
                ('doctel', models.CharField(max_length=255)),
                ('docemail', models.OneToOneField(db_column='docemail', on_delete=django.db.models.deletion.CASCADE, to='accounts.webuser')),
                ('specialties', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.specialties')),
            ],
            options={
                'db_table': 'doctor',
            },
        ),
    ]
